### ISSUE TITLE
fails at NERSC with new CFG_PATH 

### ISSUE THREAD

**Issue by RickKessler** [Samreay/Pippin#13]
pippin.sh LSST_starterKit.yml &
[1] 57463
[kessler@cori08 pippin]$ ERROR:root:Unable to find relative path inputs when searching through the data directories: ['/global/cfs/cdirs/desc-sn/pippin']
ERROR:root:Data dir inputs cannot be resolved!
Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/groups/SN/pippin/run.py", line 135, in <module>
    run(args)
  File "/global/cfs/cdirs/lsst/groups/SN/pippin/run.py", line 87, in run
    global_config = get_config(initial_path=cfg, overwrites=overwrites)
  File "/global/cfs/cdirs/desc-sn/pippin/pippin/config.py", line 22, in get
    instance = fn(*args, **kwargs)
  File "/global/cfs/cdirs/desc-sn/pippin/pippin/config.py", line 59, in get_config
    assert updated is not None
AssertionError

**Comment by Samreay** [comment]
Can you put the yml file in here as well for me, along with the cfg.yml, and Ill have a look first thing in the morning
